debian/build-bin/objs/ngx_http_xslt_filter_module.so usr/lib/freenginx/modules
debian/build-bin/objs/ngx_http_image_filter_module.so usr/lib/freenginx/modules
debian/build-bin/objs/ngx_http_geoip_module.so usr/lib/freenginx/modules
debian/build-bin/objs/ngx_http_perl_module.so usr/lib/freenginx/modules
debian/build-bin/objs/ngx_stream_geoip_module.so usr/lib/freenginx/modules
debian/build-bin/objs/ngx_mail_module.so usr/lib/freenginx/modules
debian/build-bin/objs/ngx_stream_module.so usr/lib/freenginx/modules
debian/modules_conf/* usr/share/freenginx/modules-available 
